import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { ConfigProvider } from "antd";
import Footer from "./components/Footer";
import { Suspense, useEffect } from "react";

export const metadata: Metadata = {
  title: "EduDocs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <link rel="icon" href="/favicon.png" sizes="any"/>
      <body >
        <ConfigProvider
        theme={{
          components: {
            Button: {
              colorPrimary: "#78A083",
              colorPrimaryBgHover: "#fff",
              colorPrimaryHover: "#78A083"
            }
          }
        }}>
        {children}
        </ConfigProvider>
        <Suspense fallback={<></>}/>
        <Footer/>
        </body>
    </html>
  );
}

